banner themes/uzbek/banner/background.png
banner_scale fillscreen

small_icon_size 50
big_icon_size 70
icons_dir themes/uzbek/icons

selection_big themes/uzbek/selection/big.png
selection_small themes/uzbek/selection/small.png

hideui hints,label,badges
