banner themes/rEFInd-nils/banner/background.png
banner_scale fillscreen

small_icon_size 50
big_icon_size 190
icons_dir themes/uzbek/icons

selection_big themes/rEFInd-nils/selection/big.png
selection_small themes/rEFInd-nils/selection/small.png

hideui hints,label,badges

showtools hidden_tags, reboot, shutdown, exit
